
PANTALLA_ANCHO = 1000
PANTALLA_ALTO = 1000
RESOLUCION_PANTALLA = (PANTALLA_ANCHO, PANTALLA_ALTO)
COLOR_GRIS_OSCURO = (128, 128, 128)
COLOR_GRIS_CLARO = (192, 192, 192)
COLOR_NARANJA = (245, 49, 7)
COLOR_ROJO = (255, 0, 0)

FILAS_FACIL = 8
FILAS_MEDIO = 16
FILAS_DIFICIL = 30
COLUMNAS_FACIL = 8
COLUMNAS_MEDIO = 16
COLUMNAS_DIFICIL = 30
CANTIDAD_MINAS_FACIL = 10
CANTIDAD_MINAS_MEDIO = 40
CANTIDAD_MINAS_DIFICIL = 100

TAMANIO_FUENTE_INICIO = 30
TAMANIO_FUENTE_JUGANDO = 52
TAMANIO_FUENTE_MOSTRAR_PUNTAJE = 60

TAMANIO_FUENTE_ELIGE_NIVEL = 70

TAMANIO_FUENTE_CASILLEROS_DIFICIL = 15
TAMANIO_FUENTE_CASILLEROS_MEDIO = 24
TAMANIO_FUENTE_CASILLEROS_FACIL = 52